Change how the language selection menu is implemented
 * Move info_cfg files into menus/sgd_locale and change their format
 * slightly.

 * info_cfg files now contain a variable $lang_code, wich is set to the
 * two letter language code for the translation in question, and
 * $lang_name which is the name of the language in that language.

 * Language menu now uses the name of the language in that language,
 * rather than the name of the language in English.

 * Adding new translations is made easier by automating the creation of
 * new info_cfg files in grub-mkrescue whenever a new po file is
 * created. This way translators should hopefully not need to know
 * anything about Super GRUB2 Disks translation system other than how to
 * work with gettext.

 * Document how to add new translations in the new system in
 * TRANSLATION.

 * Remove set -x from grub-mkrescue to make it easier to notice message
 * to translators, and to make any error messages easier to see (so they
 * aren't lost in the flood of normal output).

diff --git a/supergrub-mkrescue b/supergrub-mkrescue
--- a/supergrub-mkrescue
+++ b/supergrub-mkrescue
@@ -1,4 +1,4 @@
-#!/bin/bash -ex
+#!/bin/bash -e
 usage() {
 cat <<EOF
 
@@ -48,11 +48,30 @@ fi
 cp AUTHORS COPYING "$overlay/boot/grub/"
 
 # Generate mo files and add them to overlay
-mkdir "$overlay/boot/grub/sgd_locale/"
 for pofile in po/*.po; do
   basename=${pofile##*/}
-  moname="${basename%.po}.mo"
-  msgfmt "$pofile" --output-file="$overlay/boot/grub/sgd_locale/$moname"
+  lang_code="${basename%.po}"
+  info_cfg="menus/sgd_locale/${lang_code}_info.cfg"
+  msgfmt "$pofile" --output-file="$overlay/boot/grub/sgd_locale/${lang_code}.mo"
+  if ! [[ -f "$info_cfg" ]]; then
+    echo "Thank you for providing a new translation for Super GRUB2 Disk!"
+    echo "Before this translation can be used in Super GRUB2 Disk we need to know what"
+    echo "to call it in our language selection menu."
+    echo "We need to know the name of the language you've translated, in that language."
+    echo "For example, for Spanish you would enter \"Español\" (without the quotes)."
+    echo -n "Please enter the name of the language for $pofile: "
+    read language_name
+    cp info_cfg_header.cfg "$info_cfg"
+    echo "lang_code='${lang_code}'" >> "$info_cfg"
+
+    # This will fail if $language_name contains a single quote character.
+    # TODO: Fix aforementioned problem by escaping quotes in $language_name.
+    echo "language_name='${language_name}'" >> "$info_cfg"
+
+    echo "A file, ${info_cfg}, was created with this information."
+    echo "Thanks again for contributing a new translation!"
+    echo; echo
+  fi
 done
 
 grub-mkrescue $default_options
